### ISSUE TITLE
How does jupyter implement clustering

### ISSUE THREAD

**Issue by xhsky** [jupyter-server/jupyter_server#1015]

**Comment by kevin-bates** [comment]
Hi @xhsky - could you please more specific?  I'm assuming by _clustering_ you're asking about the ability to run multiple jupyter servers behind a load balancer, shared filesystems, etc., but want to be clear before proceeding.

**Comment by xhsky** [comment]
> Hi @xhsky - could you please more specific? I'm assuming by _clustering_ you're asking about the ability to run multiple jupyter servers behind a load balancer, shared filesystems, etc., but want to be clear before proceeding.

Whether the jupyter server itself has a high availability or load cluster configuration (not found in the documentation), if not, I will use nginx load proxy, I don't know if there is any problem

**Comment by kevin-bates** [comment]
Thank you for the clarification.

No, jupyter server does not currently support a cluster configuration capability.  Should you set up a load balancer, you'll want to configure client/session affinity since the Kernel and Session managers are stateful. Content services is currently stateless (assuming a shared filesystem), but I believe the upcoming RTC (real-time collaboration) effort will be introducing state to _its_ handling of content (which presumably will be the primary content service when available).

FWIW, Jupyter Enterprise Gateway offers minimally viable HA/DR (primarily DR) functionality in the form of [_availability modes_](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/config-availability.html#availability-modes), but it's essentially a "kernel server".  There, kernel state is persisted such that a different server can _rehydrate_ the kernel's connection.  We plan on introducing similar functionality to Jupyter Server (at least relative to kernel management) at some point.

**Comment by kevin-bates** [comment]
Closing since the question has been answered.
