### ISSUE TITLE
Can jupyter server use a third-party database to store sessions, and how?

### ISSUE THREAD

**Issue by xiangzhetianlumaijing** [jupyter-server/jupyter_server#1050]
Multiple jupyter servers need to share sessions.

**Comment by kevin-bates** [comment]
Hi @xiangzhetianlumaijing - thanks for opening this issue.

I don't think SQLite lends itself to this use case.  Seems like introducing an ORM layer like SQLAlchemy would be a great first step.  This way, more powerful, multi-user, multi-server, databases can be configured w/o impacting the application layer (theoretically).

I believe we'd be open to this kind of contribution given that we're trying to evolve the server in this fashion anyway.

**Comment by xiangzhetianlumaijing** [comment]
Thanks for your answer. Can multiple jupyter servers share the same sqlite? How to configure the IPs and ports' information of sqlite?

**Comment by kevin-bates** [comment]
My (limited) understanding is that SQLite is an _embedded_ database meaning that it's only available to a single process/application.  I believe others have tried having multiple applications share the same database file, but have run into issues (I believe I've run across SO posts of this nature), probably because you really need a _service_ to manage concurrency and locking at that level (like more powerful databases provide).

If we had an abstraction layer, perhaps as thin as something like SQLAlchemy, then users _should_ be able to swap out the database provider behind the abstraction layer.

**Comment by xiangzhetianlumaijing** [comment]
Thanks.

**Comment by kevin-bates** [comment]
@xiangzhetianlumaijing - we discussed this in our server meeting and I've opened a general discussion issue.  I encourage you to follow (and participate) in these discussions.  We'd love to hear from you.

I'm going to close this issue since it was more of a question that has been answered (albeit not necessarily what you wanted to hear).  Hopefully, we can address things in a more productive manner down the road.
