### ISSUE TITLE
Passing arguments to identity_provider_class and authorizer_class

### ISSUE THREAD

**Issue by greenpau** [jupyter-server/jupyter_server#1146]
I am working on authentication and authorization plugin for the integration with Caddy Security (https://authp.github.io/).

Created the following config file:

```
import os
import jupyter_caddy_security
c = get_config()
c.ServerApp.ip = '*'
c.ServerApp.port = 8128
c.ServerApp.default_url = '/lab/'
c.ServerApp.identity_provider_class = jupyter_caddy_security.CaddySecurityAuthenticator
c.ServerApp.authorizer_class = jupyter_caddy_security.CaddySecurityAuthorizer
```

What is the way to provide configuration to the `identity_provider_class` and `authorizer_class`? For example, I want to provide Caddy Security URL.

**Comment by kevin-bates** [comment]
Hi @greenpau.  

Since `identity_provider_class` and `authorizer_class` derive from `LoggingConfigurable`, and assuming your custom attributes are derivations of [`Configurable`](https://github.com/ipython/traitlets/blob/278e5242484536f04d47ce5bf2dcc67348ac533e/traitlets/config/configurable.py#L45), configuration settings for your custom instances should be settable via `c.CaddySecurityAuthenticator.my_configurable_trait = 'foo'`, for example, within that same config file.

**Comment by greenpau** [comment]
Thank you, @kevin-bates ! I did exactly that.

https://github.com/greenpau/jupyter-caddy-security

**Comment by greenpau** [comment]
Note, that you can read `server` and `log` from the `kwargs` passed to `class YourCustomAuthenticator(IdentityProvider):`

```py
        for key, value in kwargs.items():
            if key == 'log':
                self.log = value
            elif key == 'parent':
                self.server = value
```

https://github.com/greenpau/jupyter-caddy-security/blob/bfe711cdc6fa5a1cf297ae79f69bd333de5c767c/jupyter_caddy_security/authenticator.py#L10-L25
