### ISSUE TITLE
Do not check if hidden if hidden files are allowed

### ISSUE THREAD

**Issue by vidartf** [jupyter-server/jupyter_server#1224]
## Description

Currently, even if `allow_hidden` is set to true, we still call the potentially expensive check for each and every file. The clauses in the conditional should be switched so that it short-circuits on the setting.

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by vidartf** [comment]
Also, does the async file manager not need to await the is_hidden calls?

**Comment by kevin-bates** [comment]
> Also, does the async file manager not need to await the is_hidden calls?

There are two `is_hidden` methods in play here.  One takes two parameters and is a synchronous library function from `jupyter_core`, and the other is a class method defined on the respective contents manager classes, with `AsyncFileContentsManager`'s `is_hidden()` being async.  It looks like the references in AFCM are to the library function.

Frankly, I don't think AFCM's `is_hidden, `dir_exists`,  and `file_exists` don't need to exist (and I suspect there may be others like that).  If these were to be removed, the handlers will also need to be updated since they currently `ensure_async` on these.
