### ISSUE TITLE
Should get_secure_cookie set token_authenticated property?

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/jupyter_server#566]
Should this branch set `handler._token_authenticated = True`.

Technically it is "cookie authenticated", however, the cookie is based on an earlier token.

I ask because it can be useful for a handler to know when token authorisation is in use, for example:

```python
class MyExtensionHandler(ExtensionHandlerMixin, JupyterHandler):  

    @tornado.web.authenticated
    def get(self):
        user = self.get_current_user()                                           
        if self.token_authenticated:
            user = getpass.getuser()
        self.write(f'hello {user}') 
```

_Originally posted by @oliver-sanders in https://github.com/jupyter-server/jupyter_server/pull/562#discussion_r678414865_

**Comment by vidartf** [comment]
This docstring seems explanatory of intent:
https://github.com/jupyter-server/jupyter_server/blob/40c477bd1afd09b00fc69e008dc59569838ae963/jupyter_server/auth/login.py#L146-L154

**Comment by vidartf** [comment]
So if no one is complaining about the current behavior I would argue for leaving `token_authenticated` as it currently is (changing it would make things more permissible in certain scenarios, so would need to be carefully reviewed) and adding another property if needed.

**Comment by vidartf** [comment]
For the branch where the comment were made:

https://github.com/oliver-sanders/jupyter_server/blob/c8a343811631d50ad49009862aa674b18be6b86f/jupyter_server/auth/login.py#L172-L176

I don't think we can assume that the source of the secure cookie is always from a token? Or am I missing something?

**Comment by oliver-sanders** [comment]
Thanks all for looking into this and your comments, I have convinced myself the answer to this question is no, please close this issue.

The root cause for raising this was handling the difference between hub and token authentication.

With "hubless" token authentication `get_current_user` returns the token as a string (or as string or bytes in earlier versions of Jupyter Server).

> Note: `get_current_user` can also return the string `anonymous` so testing if the returned user is a string isn't a secure way of determining if the request was token authenticated?

With hub authentication `get_current_user` returns a dictionary containing the following fields:

* kind
* name
* admin
* groups
* server
* pending
* created
* last_activity
* servers

The "name" field is relevant to hubless authentication, the "server" field might be, once we have authorisation in the "kind" and "groups" fields might be relevant too.

We could potentially smooth over the difference by returning a dict in these circumstances something like:

```python
return {
    'kind': 'user',
    'user': getpass.getuser()
}
```

**Comment by Zsailer** [comment]
Thank you for further investigating this, @oliver-sanders. Closing this for now, but I'm guessing we will revisit this further as we move to make the server more multi-user.
