### ISSUE TITLE
Allow non-empty directory deletion for windows through settings

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/jupyter_server#570]
Hey would it be ok to allow non-empty directory deletion for windows through settings?

https://github.com/jupyter-server/jupyter_server/blob/f914126d173dde7d2b2f6a6d474648060c823419/jupyter_server/services/contents/filemanager.py#L492

**Comment by Zsailer** [comment]
This was discussed at last week's Jupyter Server meeting. 

I don't see a lot of downside to adding this as a configurable trait (with `default=False`). 

Unfortunately, today we have different behavior depending on OS. I think the only way for this difference to go away is to wait until `send2trash` fixes this [open issue](https://github.com/arsenetar/send2trash/issues/28)—Windows hard deletes directory when trash is full. Once this issue is fixed, we'll need to deprecate this trait.

**Comment by fcollonval** [comment]
Thanks @Zsailer for the reply. I will open a PR. Another use case for this is for integration tests. There is no simple way to remove the data folder; this will unlock it.

> FYI galata has a workaround to delete folder by deleting its content recursively. But this is so inefficient...
